export const COFFEE_BRANDS = 'COFFEE_BRANDS';
export const COFFEE_COMPANIES_ONE = 'COFFEE_COMPANIES_ONE';
export const COFFEE_COMPANIES_TWO = 'COFFEE_COMPANIES_TWO';
export const CONNECTION = 'CONNECTION';